openapi: 3.0.3
info:
  title: Kafka Poc
  contact:
    email: ffournel.pro@gmail.com
  description: |
    Cette application offre les fonctionnalités suivantes :
      - Gestion des personnes
  license:
    name: Private
  version: "1.0.0"
servers:
  - url: http://localhost:8080/api/
tags:
  - description: "Gestion des personnes
      Permet de gérer des personnes"
    name: personne
  - description: "Gestion des comptes utilisateurs
      Permet de gérer des comptes utilisateurs"
    name: account
  - description: "Gestion des notifications
      Permet de gérer les notifications"
    name: notification
paths:
  /notification:
    get:
      summary: Retourne le prochain message de notification
      description: Prochain message de notification
      operationId: getNotification
      #      security:
      #        - BearerAuth:
      #            - produits:read
      #        - basicAuth:
      #            - produits:read
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonNotification'
          description: Successful operation
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
        "404":
          $ref: '#/components/responses/NotFound'
      tags:
        - notification
      x-contentType: '*/*'
      x-accepts: application/json
      x-tags:
        - tag: notification
  /person/{id}:
    get:
      summary: Retourne une personne
      description: Retourne une personne à partir de son identifiant
      operationId: getPerson
#      security:
#        - BearerAuth:
#            - produits:read
#        - basicAuth:
#            - produits:read
      parameters:
        - name: id
          description: Identifiant unique de l'entité personne à récupérer.
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonDto'
          description: Successful operation
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
        "404":
          $ref: '#/components/responses/NotFound'
      tags:
        - personne
      x-contentType: '*/*'
      x-accepts: application/json
      x-tags:
        - tag: personne
  /person/all:
    get:
      summary: Retourne la liste des personnes
      description: Retourne l'ensemble des personnes
      operationId: getPersons
      #      security:
      #        - BearerAuth:
      #            - produits:read
      #        - basicAuth:
      #            - produits:read
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PersonDto'
          description: Successful operation
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
        "404":
          $ref: '#/components/responses/NotFound'
      tags:
        - personne
      x-contentType: '*/*'
      x-accepts: application/json
      x-tags:
        - tag: personne
  /person/generate:
    get:
      summary: Genère une personne
      description: Genère une personne avec son adresse
      operationId: generatePerson
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonDto'
          description: Successful operation
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
        "404":
          $ref: '#/components/responses/NotFound'
      tags:
        - personne
      x-contentType: '*/*'
      x-accepts: application/json
      x-tags:
        - tag: personne
  /person/createOrUpdate:
    post:
      summary: Crée ou maj une personne
      description: Crée ou maj une personne en postant son contenu
      operationId: createOrUpdatePerson
#      security:
#        - BearerAuth:
#            - produits:write
#        - basicAuth:
#            - produits:write
      parameters:
        - name: sendNotification
          description: Envoi une notification de la personne créee ou maj (default false)
          in: query
          required: false
          schema:
            type: boolean
      requestBody:
        description: Contenu de la personne à créer ou maj
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/PersonDto'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonDto'
          description: successful operation
        "400":
          content: { }
          description: Impossible de créer ou maj la personne (duplication)
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
      tags:
        - personne
      x-codegen-request-body-name: personneSk
      x-contentType: '*/*'
      x-accepts: application/json
      x-tags:
        - tag: personne
  /account/{id}:
    get:
      summary: Retourne un compte utilisateur
      description: Retourne un compte utilisateur à partir de son identifiant
      operationId: getAccount
      #      security:
      #        - BearerAuth:
      #            - produits:read
      #        - basicAuth:
      #            - produits:read
      parameters:
        - name: id
          description: Identifiant unique de l'entité compte utilisateur à récupérer.
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountDto'
          description: Successful operation
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
        "404":
          $ref: '#/components/responses/NotFound'
      tags:
        - account
      x-contentType: '*/*'
      x-accepts: application/json
      x-tags:
        - tag: account
  /account/all:
    get:
      summary: Retourne la liste des comptes utilisateurs
      description: Retourne l'ensemble comptes utilisateurs
      operationId: getAccounts
      #      security:
      #        - BearerAuth:
      #            - produits:read
      #        - basicAuth:
      #            - produits:read
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountDto'
          description: Successful operation
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
        "404":
          $ref: '#/components/responses/NotFound'
      tags:
        - account
      x-contentType: '*/*'
      x-accepts: application/json
      x-tags:
        - tag: account
  /account/createOrUpdate:
    post:
      summary: Crée ou maj un compte utilisateur
      description: Crée ou maj un compte utilisateur en postant son contenu
      operationId: createOrUpdateAccount
      #      security:
      #        - BearerAuth:
      #            - produits:write
      #        - basicAuth:
      #            - produits:write
      requestBody:
        description: compte utilisateur à créer ou maj
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/AccountDto'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountDto'
          description: successful operation
        "400":
          content: { }
          description: Impossible de créer ou maj la personne (duplication)
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
      tags:
        - account
      x-codegen-request-body-name: accountSk
      x-contentType: '*/*'
      x-accepts: application/json
      x-tags:
        - tag: account
components:
  responses:
    Success:
      description: Successful operation
      content: {}
    BadRequest:
      description: Error in client request
      content: {}
    Unauthorized:
      description: Authentication failed
      content: {}
    Forbidden:
      description: User does not have permission to access the specified resource
      content: {}
    NotFound:
      description: The resource can't be found
      content: {}
    ConflictOnDelete:
      description: The specified resource can't be deleted due to a conflict with the current state.
      content: {}
  schemas:
    AddressDto:
      description: Représentation d'une adresse
      properties:
        street:
          description: Rue
          type: string
          minLength: 3
        city:
          description: Ville
          type: string
          minLength: 3
        zipcode:
          description: code postal
          type: integer
          format: int64
      required:
        - street
        - city
        - zipcode
      xml:
        name: AddressDto
      example:
        street: 10 rue du bourbonnais
        city: Lyon
        zipcode: 69009
    PersonDto:
      description: Représentation complète d'une personne
      properties:
        id:
          description: Identifiant de la personne
          type: integer
          format: int64
        firstname:
          description: Prénom personne
          type: string
          minLength: 3
        lastname:
          description: Nom peronne
          type: string
          minLength: 3
        age:
          description: Age peronne
          type: integer
          format: int32
          minimum: 0
          maximum: 999
        address:
          description: Adresse de la personne
          type: object
          $ref: '#/components/schemas/AddressDto'
      required:
        - firstname
        - lastname
        - age
        - address
      xml:
        name: PersonDto
      example:
        id: 123
        firstname: François
        lastname: Fournel
        age: 45
    AccountDto:
      description: Représentation d'un compte client
      properties:
        id:
          description: Identifiant du compte client
          type: integer
          format: int64
        login:
          description: Login du compte
          type: string
          minLength: 3
        password:
          description: Mot de passe du compte
          type: string
          minLength: 3
        personId:
          description: Identifiant de la personne liée au compte client
          type: integer
          format: int64
        person:
          description: Person liée au compte client
          type: object
          $ref: '#/components/schemas/PersonDto'
      required:
        - login
        - password
        - personId
      xml:
        name: AccountDto
      example:
        id: 123
        login: ffournel
        password: mypass
        personId: 1
        person:
          id: 1
          firstname: francois
          lastname: fournel
          age: 45
    PersonNotification:
      description: Représentation complète d'une notification sur une personne
      properties:
        notification:
          description: Message de la notification.
          type: string
        personne:
          description: La personne sujette à la notification
          $ref: '#/components/schemas/PersonDto'
      xml:
        name: PersonNotification